query_module_inventory:
  fields:
    module_address:
      example: "05"
      required: false
      selector:
        text:

send_button_press:
  fields:
    address:
      example: "84DFFC"
      required: true
      selector:
        text:
